config/routes.rb
Rails.application.routes.draw do
  resources :dealers

  resources :bike_photos

  resources :bikes

  resources :brands

  resources :brands do
    resources :bikes, :controller => 'brand_bikes'
  end

end

app/models/bike.rb
class Bike < ActiveRecord::Base
  belongs_to :brand
  has_many :bike_photos
  has_many :dealers
  accepts_nested_attributes_for :bike_photos, allow_destroy: true
end

app/models/bike_photo.rb
class BikePhoto < ActiveRecord::Base
  belongs_to :bike
  mount_uploader :photo, PhotoUploader
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  mount_uploader :photo, PhotoUploader
  has_many :bikes
end

app/models/dealer.rb
class Dealer < ActiveRecord::Base
  belongs_to :bike
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bike_photos_controller.rb
class BikePhotosController < ApplicationController
  before_action :set_bike_photo, only: [:show, :edit, :update, :destroy]

  respond_to :html, :json

  def index
    @bike_photos = BikePhoto.all
    respond_with(@bike_photos)
  end

  def show
    respond_with(@bike_photo)
  end

  def new
    @bike_photo = BikePhoto.new
    respond_with(@bike_photo)
  end

  def edit
  end

  def create
    @bike_photo = BikePhoto.new(bike_photo_params)
    @bike_photo.save
    respond_with(@bike_photo)
  end

  def update
    @bike_photo.update(bike_photo_params)
    respond_with(@bike_photo)
  end

  def destroy
    @bike_photo.destroy
    respond_with(@bike_photo)
  end

  private
    def set_bike_photo
      @bike_photo = BikePhoto.find(params[:id])
    end

    def bike_photo_params
      params.require(:bike_photo).permit(:bike_id, :photo)
    end
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  before_action :set_bike, only: [:show, :edit, :update, :destroy]

  respond_to :html, :json
  INPUT_PHOTO_COUNT = 10

  def index
    @bikes = Bike.all
    respond_with(@bikes)
  end

  def show
    @bike_photos = @bike.bike_photos.all
    @bike_dealers = @bike.dealers
    respond_with(@bike)
  end

  def new
    @brands = Brand.all
    @bike = Bike.new
    @bike_photo = @bike.bike_photos.build
    respond_with(@bike)
  end

  def edit
    @brands = Brand.all
    @bike_photos = @bike.bike_photos.all
  end

  def create
    @bike = Bike.new(bike_params)
    @bike.save
    params[:bike_photos]['photo'].each do |photo|
      @bike_photo = @bike.bike_photos.create!(photo: photo, bike_id: @bike.id)
    end
#    print params[:bike]
#    INPUT_PHOTO_COUNT.times do |count|
#      if params[:"bike[#{count}]"] != nil
#        bike_photo = BikePhoto.new
#        bike_photo.bike_id = @bike.id
#        bike_photo.photo = params[:"bike[#{count}]"]
#        bike_photo.save
#      end
#    end

    respond_with(@bike)
  end

  def update
    @bike.update(bike_params)
    if params[:bike_photos]
      @bike.bike_photos.map {|photo| photo.destroy!}
      params[:bike_photos]['photo'].each do |photo|
        @bike_photo = @bike.bike_photos.create!(photo: photo, bike_id: @bike.id)
      end
    end
    respond_with(@bike)
  end

  def destroy
    @bike.destroy
    respond_with(@bike)
  end

  private
    def set_bike
      @bike = Bike.find(params[:id])
    end

    def bike_params
      params.require(:bike).permit(:name, :summary, :brand_id, :price, bike_photos_attributes: [:id, :bike_id, :photo])
    end
end

app/controllers/brand_bikes_controller.rb
class BrandBikesController < ApplicationController
  before_action :set_brand_bike, only: [:show, :edit, :update, :destroy]

  # GET /brand_bikes
  # GET /brand_bikes.json
  def index
    @brand_bikes = Brand.find(params[:brand_id]).bikes
  end

  # GET /brand_bikes/1
  # GET /brand_bikes/1.json
  def show
  end

  # GET /brand_bikes/new
  def new
    @brand_bike = BrandBike.new
  end

  # GET /brand_bikes/1/edit
  def edit
  end

  # POST /brand_bikes
  # POST /brand_bikes.json
  def create
    @brand_bike = BrandBike.new(brand_bike_params)

    respond_to do |format|
      if @brand_bike.save
        format.html { redirect_to @brand_bike, notice: 'Brand bike was successfully created.' }
        format.json { render :show, status: :created, location: @brand_bike }
      else
        format.html { render :new }
        format.json { render json: @brand_bike.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brand_bikes/1
  # PATCH/PUT /brand_bikes/1.json
  def update
    respond_to do |format|
      if @brand_bike.update(brand_bike_params)
        format.html { redirect_to @brand_bike, notice: 'Brand bike was successfully updated.' }
        format.json { render :show, status: :ok, location: @brand_bike }
      else
        format.html { render :edit }
        format.json { render json: @brand_bike.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brand_bikes/1
  # DELETE /brand_bikes/1.json
  def destroy
    @brand_bike.destroy
    respond_to do |format|
      format.html { redirect_to brand_bikes_url, notice: 'Brand bike was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand_bike
      @brand_bike = BrandBike.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brand_bike_params
      params[:brand_bike]
    end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: [:show, :edit, :update, :destroy]

  respond_to :html, :json

  def index
    @brands = Brand.all
    respond_with(@brands)
  end

  def show
    @bikes = @brand.bikes
    respond_with(@brand)
  end

  def new
    @brand = Brand.new
    respond_with(@brand)
  end

  def edit
  end

  def create
    @brand = Brand.new(brand_params)
    @brand.save
    respond_with(@brand)
  end

  def update
    @brand.update(brand_params)
    respond_with(@brand)
  end

  def destroy
    @brand.destroy
    respond_with(@brand)
  end

  private
    def set_brand
      @brand = Brand.find(params[:id])
    end

    def brand_params
      params.require(:brand).permit(:name, :photo, :summary)
    end
end

app/controllers/dealers_controller.rb
class DealersController < ApplicationController
  before_action :set_dealer, only: [:show, :edit, :update, :destroy]

  respond_to :html, :json

  def index
    @dealers = Dealer.all
    respond_with(@dealers)
  end

  def show
    respond_with(@dealer)
  end

  def new
    @dealer = Dealer.new
    @bikes = Bike.all
    respond_with(@dealer)
  end

  def edit
    @bikes = Bike.all
  end

  def create
    @dealer = Dealer.new(dealer_params)
    @dealer.save
    respond_with(@dealer)
  end

  def update
    @dealer.update(dealer_params)
    respond_with(@dealer)
  end

  def destroy
    @dealer.destroy
    respond_with(@dealer)
  end

  private
    def set_dealer
      @dealer = Dealer.find(params[:id])
    end

    def dealer_params
      params.require(:dealer).permit(:name, :address, :summary, :bike_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bike_photos_helper.rb
module BikePhotosHelper
end

app/helpers/bikes_helper.rb
module BikesHelper
end

app/helpers/brand_bikes_helper.rb
module BrandBikesHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/dealers_helper.rb
module DealersHelper
end

app/views/bike_photos/_form.html.erb
<%= form_for(@bike_photo) do |f| %>
  <% if @bike_photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bike_photo.errors.count, "error") %> prohibited this bike_photo from being saved:</h2>

      <ul>
      <% @bike_photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :bike_id %><br>
    <%= f.number_field :bike_id %>
  </div>
  <div class="field">
    <%= f.label :photo %><br>
    <%= f.text_field :photo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bike_photos/edit.html.erb
<h1>Editing bike_photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @bike_photo %> |
<%= link_to 'Back', bike_photos_path %>

app/views/bike_photos/index.html.erb
<h1>Listing bike_photos</h1>

<table>
  <thead>
    <tr>
      <th>Bike</th>
      <th>Photo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bike_photos.each do |bike_photo| %>
      <tr>
        <td><%= bike_photo.bike_id %></td>
        <td><%= bike_photo.photo %></td>
        <td><%= link_to 'Show', bike_photo %></td>
        <td><%= link_to 'Edit', edit_bike_photo_path(bike_photo) %></td>
        <td><%= link_to 'Destroy', bike_photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bike photo', new_bike_photo_path %>

app/views/bike_photos/new.html.erb
<h1>New bike_photo</h1>

<%= render 'form' %>

<%= link_to 'Back', bike_photos_path %>

app/views/bike_photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bike:</strong>
  <%= @bike_photo.bike_id %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @bike_photo.photo %>
</p>

<%= link_to 'Edit', edit_bike_photo_path(@bike_photo) %> |
<%= link_to 'Back', bike_photos_path %>

app/views/bikes/_form.html.erb
<%= form_for(@bike) do |f| %>
  <% if @bike.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bike.errors.count, "error") %> prohibited this bike from being saved:</h2>

      <ul>
      <% @bike.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.select(:brand_id, @brands.collect{|t| [t.name, t.id]}, :prompt => (t"select_brand")) %>
  </div>
  <div class="field">
    <%= f.label :summary %><br>
    <%= f.text_area :summary %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <!--
  <%= f.fields_for :bike_photos do |p| %>
      <div class="field">
        <%= p.label :photo %><br>
        <%= p.file_field :photo, :multiple => true, name: "bike_photos[photo][]" %>
      </div>
  <% end %>
  -->
  <div class="field">
    <%= f.label :photo %><br>
    <%= f.file_field :photo, :multiple => true, name: "bike_photos[photo][]" %>
  </div>
  <% if params[:controller] == "bikes" && params[:action] == "edit" %>
      <% @bike.bike_photos.each do |p| %>
          <%= image_tag p.photo %>
      <% end %>
  <% end %>

    <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bikes/edit.html.erb
<h1><%= t("edit_bike") %></h1>

<%= render 'form' %>

<%= link_to 'Show', @bike %> |
<%= link_to 'Back', bikes_path %>

app/views/bikes/index.html.erb
<h1><%= t("list_bikes") %></h1>

<table>
  <thead>
    <tr>
      <th><%= t("activerecord.attributes.bike.name") %></th>
      <th><%= t("activerecord.attributes.bike.summary") %></th>
      <th><%= t("activerecord.attributes.bike.price") %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bikes.each do |bike| %>
      <tr>
        <td><%= bike.name %></td>
        <td><%= bike.summary %></td>
        <td><%= bike.price %></td>
        <td><%= link_to 'Show', bike %></td>
        <td><%= link_to 'Edit', edit_bike_path(bike) %></td>
        <td><%= link_to 'Destroy', bike, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t("new_bike"), new_bike_path %>

app/views/bikes/new.html.erb
<h1><%= t("new_bike") %></h1>

<%= render 'form' %>

<%= link_to 'Back', bikes_path %>

app/views/bikes/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="row">
    <% @bike_photos.each do |p| %>
        <%= image_tag p.photo, :class => "col-md-12 col-xs-12 col-lg-12" %>
        <!-- <%= link_to "Edit Photo", edit_bike_photo_path(p) %> -->
    <% end %>
  </div>

  <div class="row input-item">
    <div class="col-md-4 col-xl-4 col-lg-4"><%= t("activerecord.attributes.bike.name") %></div>
    <div class="col-md-8 col-xl-8 col-lg-8 text-right"><%= @bike.name %></div>
  </div>

  <div class="row input-item">
    <div class="col-md-4 col-xl-4 col-lg-4"><%= t("activerecord.attributes.bike.summary") %></div>
    <div class="col-md-8 col-xl-8 col-lg-8 text-right"><%= @bike.summary %></div>
  </div>

  <div class="row input-item">
    <div class="col-md-4 col-xl-4 col-lg-4"><%= t("activerecord.attributes.bike.price") %></div>
    <div class="col-md-8 col-xl-8 col-lg-8 text-right"><%= @bike.price %></div>
  </div>


  <p>
    <strong><%= t("list_dealer") %></strong>
  <table>
    <% @bike_dealers.each do |dealer| %>
        <tr>
          <td><%= dealer.name %></td>
        </tr>
    <% end %>
  </table>
  </p>
  <!--
  <%= link_to 'Edit', edit_bike_path(@bike) %> |
  <%= link_to 'Back', bikes_path %>
  -->
</div>

app/views/brand_bikes/_form.html.erb
<%= form_for(@brand_bike) do |f| %>
  <% if @brand_bike.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brand_bike.errors.count, "error") %> prohibited this brand_bike from being saved:</h2>

      <ul>
      <% @brand_bike.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/brand_bikes/edit.html.erb
<h1>Editing brand_bike</h1>

<%= render 'form' %>

<%= link_to 'Show', @brand_bike %> |
<%= link_to 'Back', brand_bikes_path %>

app/views/brand_bikes/index.html.erb
<h1>Listing brand_bikes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @brand_bikes.each do |brand_bike| %>
      <tr>
        <td><%= brand_bike.name %></td>
        <td><%= link_to 'Show', brand_bike %></td>
        <td><%= link_to 'Edit', edit_bike_path(brand_bike) %></td>
        <td><%= link_to 'Destroy', brand_bike, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Brand bike', new_brand_bike_path %>

app/views/brand_bikes/new.html.erb
<h1>New brand_bike</h1>

<%= render 'form' %>

<%= link_to 'Back', brand_bikes_path %>

app/views/brand_bikes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_brand_bike_path(@brand_bike) %> |
<%= link_to 'Back', brand_bikes_path %>

app/views/brands/_form.html.erb
<%= form_for(@brand) do |f| %>
  <% if @brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
      <% @brand.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :photo %><br>
    <%= f.file_field :photo %>
  </div>
  <div class="field">
    <%= f.label :summary %><br>
    <%= f.text_area :summary %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/brands/edit.html.erb
<h1>Editing brand</h1>

<%= render 'form' %>

<%= link_to 'Show', @brand %> |
<%= link_to 'Back', brands_path %>

app/views/brands/index.html.erb
<h1><%= t("list_brands") %></h1>

<table>
  <thead>
    <tr>
      <th><%= t("activerecord.attributes.brand.name") %></th>
      <th><%= t("activerecord.attributes.brand.photo") %></th>
      <th><%= t("activerecord.attributes.brand.summary") %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @brands.each do |brand| %>
      <tr>
        <td><%= brand.name %></td>
        <td><%= image_tag brand.photo %></td>
        <td><%= brand.summary %></td>
        <td><%= link_to 'Show', brand %></td>
        <td><%= link_to 'Edit', edit_brand_path(brand) %></td>
        <td><%= link_to 'Destroy', brand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t("new_brand"), new_brand_path %>

app/views/brands/new.html.erb
<h1><%= t("new_brand") %></h1>

<%= render 'form' %>

<%= link_to 'Back', brands_path %>

app/views/brands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= t("activerecord.attributes.bike.name") %></strong>
  <%= @brand.name %>
</p>

<p>
  <strong><%= t("activerecord.attributes.bike.photo") %></strong>
  <%= image_tag @brand.photo %>
</p>

<p>
  <strong><%= t("activerecord.attributes.bike.summary") %></strong>
  <%= @brand.summary %>
</p>

<p>
  <strong><%= t("list_bikes") %></strong>
  <table>
    <% @bikes.each do |bike| %>
        <tr>
          <td><%= bike.name %></td>
        </tr>
    <% end %>
  </table>
</p>

<%= link_to 'Edit', edit_brand_path(@brand) %> |
<%= link_to 'Back', brands_path %>

app/views/dealers/_form.html.erb
<%= form_for(@dealer) do |f| %>
  <% if @dealer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dealer.errors.count, "error") %> prohibited this dealer from being saved:</h2>

      <ul>
      <% @dealer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :summary %><br>
    <%= f.text_area :summary %>
  </div>
  <div class="field">
    <%= f.label :bike_id %><br>
    <%= f.select(:bike_id, @bikes.collect{|t| [t.name, t.id]}, :prompt => (t"select_bike")) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dealers/edit.html.erb
<h1>Editing dealer</h1>

<%= render 'form' %>

<%= link_to 'Show', @dealer %> |
<%= link_to 'Back', dealers_path %>

app/views/dealers/index.html.erb
<h1><%= t("list_dealer") %></h1>

<table>
  <thead>
    <tr>
      <th><%= t("activerecord.attributes.dealer.name") %></th>
      <th><%= t("activerecord.attributes.dealer.address") %></th>
      <th><%= t("activerecord.attributes.dealer.summary") %></th>
      <th><%= t("activerecord.attributes.bike.name") %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dealers.each do |dealer| %>
      <tr>
        <td><%= dealer.name %></td>
        <td><%= dealer.address %></td>
        <td><%= dealer.summary %></td>
        <td><%= dealer.bike_id %></td>
        <td><%= link_to 'Show', dealer %></td>
        <td><%= link_to 'Edit', edit_dealer_path(dealer) %></td>
        <td><%= link_to 'Destroy', dealer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t("new_dealer"), new_dealer_path %>

app/views/dealers/new.html.erb
<h1><%= t("new_dealer") %></h1>

<%= render 'form' %>

<%= link_to 'Back', dealers_path %>

app/views/dealers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= t("activerecord.attributes.dealer.name") %></strong>
  <%= @dealer.name %>
</p>

<p>
  <strong><%= t("activerecord.attributes.dealer.address") %></strong>
  <%= @dealer.address %>
</p>

<p>
  <strong><%= t("activerecord.attributes.dealer.summary") %></strong>
  <%= @dealer.summary %>
</p>

<p>
  <strong><%= t("activerecord.attributes.bike.name") %></strong>
  <%= @dealer.bike.name %>
</p>

<%= link_to 'Edit', edit_dealer_path(@dealer) %> |
<%= link_to 'Back', dealers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BikeAPP</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag params[:controller] %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>